---
title: "벡터장의 발산과 그린정리"
number-sections: true
number-depth : 2
crossref:
  chapters: true
---
{{< include ../../latexmacros.qmd >}}

</br>


이 장에서는 평면에서의 벡터장의 발산과 그린정리를 다룬다. 여기서 @SNUCalculus2013 에서는 벡터장에 대한 연산자 $\text{div},\,\text{rot}$ 를 정하여 사용했지만 여기서는 아래와 같이 $\nabla$ 연산자를 사용하기로 한다.

$$
\boxed{
\begin{aligned}
\nabla \bcdot \bf{F} &:= \partial_x F_x + \partial_y F_y,\\[0.3em]
\nabla \times \bf{F} &:= \partial x F_y - \partial_y F_x.
\end{aligned}
}
$$

</br>

## 벡터장과 발산


### 연습문제


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_1_2} 

#### SNU 15.1.2

$n$-공간의 열린집합에서 정의된 벡터장 $\bf{F},\,\bf{G}$ 및 함수 $h$ 에 대하여

$$
\begin{aligned}
\nabla \bcdot (\bf{F}+\bf{G}) &= \nabla \bcdot \bf{F} + \nabla \bcdot \bf{G},\\[0.3em]
\nabla \bcdot (h\bf{F}) &= (\nabla h) \bcdot \bf{F} + h(\nabla \bcdot \bf{F})
\end{aligned}
$$

임을 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\sum_{i} \partial_i (\bf{F}+\bf{G})_i &= \sum_i \partial_i F_i + \sum_i \partial_i G_i =  \nabla \bcdot \bf{F} + \nabla \bcdot \bf{G},\\[0.3em]
\sum_i \partial _i (hF_i) &= \sum_i (\partial_i h) F_i + \sum_i h(\partial_i F_i) =\nabla h \bcdot \bf{F} + h\nabla \bcdot \bf{F}.
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_1_4} 

#### SNU 15.1.4

입체각 벡터장

$$
\bf{A}(X) = \dfrac{X}{|X|^3}, \qquad X\in \R^3-\{\mathcal{O}\}
$$

는 비압축장임을 보여라.
:::

</div>

::: {.solution}
$\nabla \bcdot X=3$, $\nabla |X|^{-3}=-3X/|X|^{5}$ 과 @exr-CAL_15_1_2 의 두번째 식을 이용하면

$$
\nabla \bcdot \bf{A} = 3/|X|^{3} - 3 |X|^2/|X|^{5} = 0
$$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_1_6} 

#### SNU 15.1.6

$n$-공간의 단위벡터 $\bf{v}$ 에 대하여, 벡터장

$$
\bf{F}(\bf{x}) := k(\bf{x\cdot v})\bf{v}
$$

의 발산함수를 구하라. (단 $k$ 는 상수이다.)

:::

</div>

::: {.solution}

$F_i = k (\sum_j v_jx_j) v_i$ 이므로

$$
\nabla \bcdot \bf{F} = \sum_i \partial_i \left(\sum_j x_j v_j\right)v_i = \sum_{i, j} v_j \delta_{ij}v_i = \sum_i v_i^2 = 1
$$
:::

</br>

## 평면벡터장과 발산정리

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_2_0_2} 

#### SNU 기본연습문제 2.0.2.1

좌표평면에서 점 $P$ 를 중심으로 하고 반지름의 길이가 $r$ 인 원판을 $D_r$ 이라고 하자. 이때 점 $P$ 근방에서 정의된 벡터장 $\bf{F}$ 에 대하여

$$
\nabla \bcdot \bf{F}(P) = \lim_{r \to 0}\dfrac{1}{\pi r^2} \int_{\partial D_r} \bf{F \cdot n} \, ds
$$

임을 보이라. 또 이로부터 발산의 의미를 설명하라.

:::

</div>

::: {.solution}

일반성을 잃지 않고 $P$ 를 원점으로 잡을 수 있다. 경로를 $X(t) = (r \cos \theta,\, r \sin \theta)$ 로 매개화하면 $\bf{n} = (\cos \theta,\, \sin \theta)$ 이며

$$
\begin{aligned}
\int_{\partial D_r} \bf{F\cdot n}\,ds &= \int_0^{2\pi} r(F_x\cos \theta + F_y \sin \theta ) d\theta
\end{aligned}
$$

이다. 테일러 전개를 이용하면 

$$
\bf{F}(x,\,y) = \bf{F}(\mathcal{O}) + x\partial_x F_x(\mathcal{O})\bf{i} + y\partial_y F_y(\mathcal{O})\bf{j} 
$$

이며, 따라서

$$
\begin{aligned}
\int_{\partial D_r} \bf{F\cdot n}\,ds &= \underbrace{\int_0^{2\pi} (r\cos\theta F_x(\mathcal{O})+ r \sin \theta F_y(\mathcal{O}))\,d\theta}_{\Large = 0}  \\[0.3em]
&\quad + \int_0^{2\pi} \left(r^2 \cos^2\theta \partial_x F_x(\mathcal{O}) + r^2 \sin^2\theta \partial_y F_y (\mathcal{O}) \right) \\[0.3em]
&= \pi r^2\left(\partial_x F_x(\mathcal{O}) + \partial_y F_y(\mathcal{O})\right)
\end{aligned}
$$

따라서 문제의 주어진 극한은 $\nabla \bcdot \bf{F}(P)$ 이다.

테일러 전개에서 $r^k,\, k>2$ 항은 극한에서 $\to 0$ 이므로 무시할 수 있다.

:::

</br>

## 평면 벡터장과 회전도

*연습문제 없음*

</br>

## 경계와 향

*연습문제 없음*

</br>

## 그린 정리

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_5_1} 

#### SNU 15.5.1

좌표평면에서 단위원 $x^2+y^2=1$ 을 반시게 방향으로 한바퀴 도는 곡선을 $C$ 라고 할 때, 선적분

$$
\int_C \left(e^{\text{arctan}\,x} + (xy+1) e^{xy}\right)\,dx + \left(x^3+3xy^2 +x^2e^{xy}\right)\,dy
$$

를 구하라.

:::

</div>

::: {.solution}

단위원 $D_1$ 에 대해
$$
\begin{aligned}
{}[문제의 적분] &= \int_{D_1} \left(-xe^{xy} -(x^2y+x) e^{xy} + 3x^2 + 3y^2 +2xe^{xy} + yx^2e^{xy} \right)\,dx\,dy \\[0.3em]
&=\int_{D_1}3(x^2+y^2)\,dx\,dy =3\int_{0}^{2\pi}  \int_{0}^1 r^3\,dr\,d\theta = \dfrac{3\pi}{2}
\end{aligned}
$$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_5_2} 

#### SNU 15.5.2

그린 정리를 이용하여 다음 적분을 구하라.

($1$) $\displaystyle \int_C (x+y^2)dx + (y+x^2)\,dy$, $C$ 는 네 점 $(\pm 1,\,\pm 1)을 꼭지점으로 하는 정사각형의 둘레.

($2$) $\displaystyle \int_C (x^2+y^2)dx -2xy\,dy$ $C$ 는 $x=0$, $y=0$, $x+y=1$ 로 둘러싸인 삼각형의 둘레.

($3$) $\displaystyle \int_C (y+e^x)dx + (2x^2+\cos y)\,dy$, $C$ 는 점 $(0,\,0)$, $(1,\,1)$, $(2,\,0)$ 을 꼭지점으로 하는 삼각형의 둘레.

($4$) $\displaystyle \int_C (x^2-y^2)\,dx + xy\,dy$, $C$ 는 $y=x$ 와 $y=x^2$ 으로 둘러쌓인 부분의 경계.

($5$) $\displaystyle \int_C (-y^2+e^{e^x})\,dx + (\text{arctan}\, y)\,dy$, $C$ 는 $y=x^2$ 과 $x=y^2$ 으로 둘러싸인 부분의 경계.

($6$) $\displaystyle \int_C x^2\,dy - y^2\,dx$, $C$ 는 극좌표로 $r=1+\cos\theta$ 로 주어지는 곡선.

:::

</div>

::: {.solution}

$$
\begin{aligned}
(1) \quad [\cdots] &= \int_{-1}^1 \int_{-1}^1 \left(2x - 2y\right)\,dx\,dy = 0
\end{aligned}
$$

$$
\begin{aligned}
(2) \quad [\cdots] &= \int_0^1 \int_{0}^{1-x} (-2y - 2y)\,dy\,dx = -2 \int_0^1 (1-x)^2 \,dx = -\dfrac{2}{3} 
\end{aligned}
$$

$$
\begin{aligned}
(3) \quad [\cdots] &= \int_0^1 \int_0^x (4x - 1)\,dy\,dx + \int_1^2 \int_0^{2-x} (4x-1) = 3
\end{aligned}
$$

$$
\begin{aligned}
(4) \quad [\cdots] &= \int_0^1 \int_{x^2}^x (3y)\,dy = \dfrac{1}{5}
\end{aligned}
$$


$$
\begin{aligned}
(5) \quad [\cdots] &= \int_0^1 \int_{x^2}^{\sqrt{x}} (2y)\,dy\,dx =\dfrac{3}{10}.
\end{aligned}
$$

$$
\begin{aligned}
(6) \quad [\cdots] &= \int_A (2x+2y)\,dx\,dy = \int_0^{2\pi} \int_0^{1+\cos\theta} 2r^2(\cos\theta + \sin \theta)\,dr\,d\theta = \dfrac{5\pi}{2}
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_5_3} 

#### SNU 15.5.3

그린 정리를 이용하여 $x$ 축과 사이클로이드

$$
x=a(t-\sin t),\quad y = a(1-\cos t)\qquad \quad (0\le t \le 2\pi)
$$

로 둘러쌓인 부분의 넓이를 구하라.

:::

</div>

::: {.solution}
$[Area]=-\int_{\partial D} y\,dx$ 를 이용한다 $x$ 축 위의 선은 $y=0$ 이므로 적분할 필요가 없고 주어진 곡선은 시계방향으로 돌지만 그린정리에서의 방향은 반시계 방향이므로
$$
{}[Area] = \int_0^{2\pi} a^2(1-\cos t)^2\,dt = 3\pi a^2
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_5_7} 

#### SNU 15.5.7

영역

$$
D=\{(x,\,y)\in \R^2 : y\ge 0\}
$$

에서 정의된 함수 $Q(x,\,y) := e^{-y^2} \arctan x$ 에 대하여

$$
\int_{\partial D} Q(x,\,y) \,dy \ne \iint_D \dfrac{\partial Q}{\partial x}\,dx\,dy
$$

임을 보이라. 이로부터 그린정리는 유계인 영역이 아니면 성립하지 않음을 알 수 있다.

:::

</div>

::: {.solution}

$\partial D$ 는 $y=0$ 이며 따라서
$$
\int_{\partial D} Q(x,\,y)\, dy = 0. 
$$

또한 
$$
 \iint_D \dfrac{\partial Q}{\partial x}\,dx\,dy= \int_{-\infty}^\infty \int_{0}^\infty \dfrac{1}{1 + x^2} e^{-y^2} \,dy\,dx = \pi \sqrt{\dfrac{\pi}{2}} \ne 0
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_5_8} 

#### SNU 15.5.8

평면에서 단순폐곡선 $C$ 의 내부 $D$ 가 원점을 포함하면, 각원소 벡터장 $\bf{a}$ 에 대하여

$$
\int_C \bf{a}\bcdot d\bf{s} = 2\pi, \qquad \iint_D \nabla \times \bf{a}\,dV_2=0
$$

임을 보이고,  이것이 왜 그린정리에 모순되지 않는지를 설명하라. 

:::

</div>

::: {.solution}

각원소 벡터장 $\bf{a}= -\dfrac{y}{x^2+y^2}\bf{i} + \dfrac{x}{x^2+y^2}\bf{j}$ 에 대해

$$
\begin{aligned}
\nabla \times \bf{a} &= \dfrac{1}{x^2+y^2} - \dfrac{2x^2}{(x^2+y^2)^2} + \dfrac{1}{x^2+y^2} - \dfrac{2y^2}{(x^2 + y^2)^2} =0
\end{aligned}
$$

이므로 $\iint_D \nabla \times \bf{a}\,dV_2=0$ 이다.

각원소 벡터장의 적분은 단순폐곡선에 대해 $2\pi$ 임을 안다. (@SNUCalculus2013 기본연습문제 2.4.1). 

그린정리는 영역 $D$ 의 모든 점에서 벡터장이 정의될 것을 요구하지만 각원소 벡터장은 원점에서 정의되지 않는다. 따라서 모순되지 않는다.
:::

<br>

## 탐구문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_S01} 

#### SNU 탐구문제 15.1

좌표평면 전체에서 정의된 일급함수 $h(x,\,y)$ 에 대하여

$$
\bf{F}(x,\,y) = h(x,\,y) \bf{A}(x,\,y),\qquad \bf{A}(x,\,y) := \dfrac{(x,\,y)}{x^2+y^2}
$$

라고 하자. 이 때 $\nabla \bcdot \bf{F}=0$ 이면 $h(x,\,y)$ 는 상수함수임을 보여라.

:::

</div>

::: {.solution}

$h_x = \partial_x h,\, h_y = \partial_y h$ 라고 하자. 
$$
\begin{aligned}
\nabla \bcdot \bf{F} &= (\nabla h) \bf{ \cdot A} + h (\nabla \bf{\cdot A}) \\[0.3em]
&= (\partial_x h)A_x + (\partial_y h) A_y + h \underbrace{\left(\dfrac{2}{x^2+y^2} - \dfrac{2x^2+2y^2}{(x^2+y^2)^2}\right)}_{\Large = 0} \\[0.3em]
&= \dfrac{(\partial_x h)x + (\partial_y h )y}{x^2+y^2} = 0
\end{aligned}
$$

이므로 임의의 $x,\,y$ 에 대해 

$$
(\partial_x h)x + (\partial_y h )y = 0
$$

이다. 따라서 $\partial_x h = \partial_y h = 0$ 이므로 $h$ 는 상수함수이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_S02} 

#### SNU 탐구문제 15.2

좌표평면의 한 열린 집합에서 정의된 함수 $P(x,\,y),\,Q(x,\,y)$ 와 두 벡터 $\bf{v},\,\bf{w}\in \R^2$ 에 대하여 벡터장 $\bf{F}$ 가

$$
\bf{F}(x,\,y) = P(x,\,y)\bf{v}+ Q(x,\,y)\bf{w}
$$

라고 하자. 이때

$$
\nabla \bcdot \bf{F} = D_\bf{v}P + D_\bf{w}Q
$$

임을 보이라.

:::

</div>

::: {.solution}

$\bf{v} = \sum_{i=1}^2 v_i\bf{e}_i$, $\bf{w} = \sum_{i=1}^2 w_i \bf{e}_i$ 라고 하자.

$$
\begin{aligned}
\nabla \bcdot \bf{F} &= \nabla \bcdot \left[\sum_{i=1}^2 \left(P(x,\,y)v_i + Q(x,\,y)w_i\right) \bf{e}_i\right] \\[0.3em]
&= \sum_{i=1}^2 (\partial_i P)v_i + (\partial_i Q) w_i =  D_\bf{v}P + D_\bf{w}Q
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_S03} 

#### SNU 탐구문제 15.3

좌표평면의 열린 집합 $U$ 에서 정의된 이급 벡터장

$$
\bf{F}= P(x,\,y)\bf{i} + Q(x,\,y)\bf{j}
$$

에 대하여 다음을 보여라.

($i$) 임의의 단순폐곡선 $C\subset U$ 에 대하여 $\displaystyle \int_C\bf{F}\bcdot d\bf{s} =0$ 이면 $\partial_y P = \partial_x Q$ 이다.

($ii$) 임의의 단순폐곡선 $C\subset U$ 에 대하여 $\displaystyle \int_C\bf{F}\bcdot \bf{n} ds =0$ 이면 $\partial_x P = - \partial_y Q$ 이다.

($iii$) 임의의 단순폐곡선 $C\subset U$ 에 대하여 $\displaystyle \int_C \bf{F}\bcdot d\bf{s}=0=\int_C \bf{F\cdot n}\,ds$ 이면

$$
\left(\dfrac{\partial^2}{\partial x^2} + \dfrac{\partial^2}{\partial y^2}\right) P = 0,\qquad \left(\dfrac{\partial^2}{\partial x^2} + \dfrac{\partial^2}{\partial y^2}\right) Q=0
$$

이다.

:::

</div>

::: {.solution}

($i$) $\nabla \times \bf{F}=0$.

($ii$) $\nabla \bcdot \bf{F} =0$

($iii$) $(\partial_x^2 + \partial_y^2)P=0$ 임을 보인다. $Q$ 에 대해서도 같은 방법으로 보일 수 있다.

$$
(\partial_x^2 + \partial_y^2) P = \partial_x(-\partial_y Q) + \partial_y (\partial_x Q)= -\partial_x \partial_y Q + \partial_y \partial_x Q = 0
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_S04} 

#### SNU 탐구문제 15.4

평면벡터장 $\bf{F}(x,\,y)$ 중에서

$$
\nabla \bcdot \bf{F}=0,\qquad \nabla \times \bf{F}=0
$$

인 보기를 들라.

:::

</div>

::: {.solution}

상수 벡터장.

$$
\bf{B} = \dfrac{(-y,\,x)}{x^2+y^2}
$$

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_S05} 

#### SNU 탐구문제 15.5

좌표평면에서 원점을 기준으로 점 $(x,\,y)$ 를 $90^\circ$ 회전시킨 것을 $(x,\,y)^\ast$ 라고 두자.

$$
(x,\,y)^\ast  := (-y,\,x).
$$

마찬가지로 평면 벡터장 $\bf{F}(x,\,y) = f_1(x,\,y)\bf{i} + f_2(x,\,y)\bf{j}$ 를 $90^\circ$ 회전시킨 것을 $\bf{F}^\ast$ 로 두자.

$$
\bf{F}^\ast = -f_2 \bf{i} + \bf{f}_1 \bf{j}.
$$

이제 함수 $g(x,\,y)$ 와 벡터장 $\bf{F}(x,\,y)$ 에 대하여

$$
\nabla \times (g\bf{F}) = -(\nabla g) \bcdot \bf{F}^\ast + g (\nabla \times \bf{F})
$$

를 보이라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\nabla \times (g\bf{F}) &= \partial_x (gf_2) - \partial_y (gf_1) \\[0.3em]
&=f_2 (\partial_x g) + g (\partial_x f_2) - f_1 (\partial_y g) - g(\partial_y f_1) \\[0.3em]
&= \underbrace{\left[(\partial_x g) f_2 - (\partial_y g) f_1 \right]}_{\Large = -(\nabla g) \bcdot \bf{F}^\ast} + \underbrace{g( \partial_x f_2 - \partial_y f_1)}_{\Large = g (\nabla \times \bf{F})} \\[0.3em]
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_S06} 

#### SNU 탐구문제 15.6

각원소 벡터장 $\bf{a}$ 와 일급사상 $f(r)$ 에 대하여 벡터장 $\bf{F}(x,\,y) = f(\sqrt{x^2+y^2})\bf{a}(x,\,y)$ 가 비회전장이면 $f$ 는 상수함수임을 보여라.

:::

</div>

::: {.solution} 

@exr-CAL_15_S05 의 벡터 회전 개념으로부터

$$
\bf{a}^\ast = - \dfrac{(x,\,y)}{x^2+y^2} = - \dfrac{X}{|X|^2}
$$

임을 안다. 또한 $\nabla \times \bf{a}=0$ 임을 안다. $\bf{F}$ 가 비회전장이므로 

$$
0 = \nabla \times \bf{F} = \nabla \times (f\bf{a}) = -(\nabla f)\cdot \bf{a}^\ast = \dfrac{\partial f}{\partial r}\dfrac{1}{|X|}
$$

이다. $f=f(r)$ 이므로 $\nabla f = \dfrac{\partial f}{\partial r} \dfrac{X}{|X|}$ 임을 사용하였다. 따라서 $\dfrac{\partial f}{\partial r} = 0$ 이며 $f$ 는 상수함수이다.
:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CAL_15_S07} 

#### SNU 탐구문제 15.7

벡터 $(t_1,\ldots,\,t_n)$ 과 $n$ 차 직교 행렬 $(a_{ij})$ 에 대하여 $n$-공간에 새로운 좌표계

$$
y_i = \sum_{j=1}^n a_{ij} x_j + t_i,\qquad \qquad (i=1,\ldots,\,n)
$$

가 주어졌다고 하자. 이 때 벡터장 $\bf{F}$ 의 발산은 좌표계와 무관함을 보이라.

:::

</div>

::: {.solution}

$(x_1,\ldots,\,x_n)$ 좌표계의 단위벡터를 $(\bf{e}_1,\ldots,\,\bf{e}_n)$ 이라고 하고 $(y_1,\ldots,\,y_n)$ 좌표계의 단위행렬을 $(\bf{f}_1,\ldots,\,\bf{f}_n)$ 이라고 하자 $A=(a_{ij})$ 에 대해 $A^{-1} = A^T = (a_{ji})$ 이므로 

$$
\bf{F} = \sum_j F_j \bf{e}_j = \sum_i \overline{F}_i \bf{f}_i = \sum_i \sum_j \overline{F}_i (a_{ij})^{-1}\bf{e}_j  \sum_i \sum_j \overline{F}_i a_{ji}\bf{e}_j
$$

이다. 즉

$$
F_j = \sum_i a_{ji}\overline{F}_i 
$$

이다. 이로부터,

$$
\begin{aligned}
\sum_i \dfrac{\partial F_i}{\partial x_i} &= \sum_i \sum_j \dfrac{\partial y_j}{\partial x_i}\dfrac{\partial F_i}{\partial y_j} = \sum_{j, k} \underbrace{\sum_i a_{ji} a_{ik}}_{\large = \delta_{jk}} \dfrac{\partial \overline{F}_k}{\partial y_j} \\[0.3em]
&= \sum_{j} \dfrac{\partial \overline{F}_j}{\partial y_j}
\end{aligned}
$$
:::